name: iOS CI

on:
  push:
    branches: [ "main", "testing_branch", "default" ]
  pull_request:
    branches: [ "main", "default" ]

jobs:
  build_and_test:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Default Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.app/Contents/Developer

      - name: Run Unit & UI Tests
        run: |
          xcodebuild clean test \
            -project SkyBarber_iOS.xcodeproj \
            -scheme SkyBarber_iOS \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
